import pandas as pd
from fpdf import FPDF
import io
import re

# ══════════════════════════════════════════════════════════════════════════════
# DOWNLOADER MODULE
# Handles export of reports as TXT and PDF
# ══════════════════════════════════════════════════════════════════════════════

def report_to_txt(report_text):
    """Convert report text to bytes for download."""
    return report_text.encode("utf-8")


def report_to_pdf(report_text, title="AI Data Analyst Report"):
    """
    Convert the AI report text to a PDF using fpdf2.
    Returns PDF as bytes.
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Title ─────────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(102, 126, 234)   # Purple
    pdf.cell(0, 12, "AI Data Analyst Report", ln=True, align="C")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8, "Created by Jeevan Bhatkar | Powered by Claude AI", ln=True, align="C")
    pdf.ln(4)

    # ── Divider ───────────────────────────────────────────────────────────────
    pdf.set_draw_color(102, 126, 234)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # ── Body ──────────────────────────────────────────────────────────────────
    # Strip markdown symbols for PDF
    clean_text = re.sub(r"[╔╗╚╝║═─]", "", report_text)

    for line in clean_text.split("\n"):
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue

        # Section headers (## prefix)
        if line.startswith("## "):
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(102, 126, 234)
            pdf.multi_cell(0, 8, line.replace("## ", ""), ln=True)
            pdf.set_draw_color(220, 220, 240)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(2)

        # Bold items (** prefix)
        elif line.startswith("**") and line.endswith("**"):
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(50, 50, 80)
            pdf.multi_cell(0, 7, line.replace("**", ""), ln=True)

        # Bullet points
        elif line.startswith("- ") or line.startswith("• "):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(60, 60, 60)
            clean = line.lstrip("- •").strip()
            pdf.multi_cell(0, 6, f"  • {clean}", ln=True)

        # Normal text
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(60, 60, 60)
            # Sanitize: remove non-latin1 characters
            safe = line.encode("latin-1", errors="replace").decode("latin-1")
            pdf.multi_cell(0, 6, safe, ln=True)

    # ── Footer ────────────────────────────────────────────────────────────────
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(180, 180, 180)
    pdf.cell(0, 8, "Generated by AI Data Analyst | Jeevan Bhatkar", align="C")

    return bytes(pdf.output())